// Generated by https://quicktype.io

export type Post = {
  contents: Content[];
  totalCount: number;
  offset: number;
  limit: number;
};

export type Content = {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  body: string;
  category: Category[];
  image?: Image;
};

export type Category = {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
};

export type Image = {
  url: string;
};
