// Generated by https://quicktype.io

export interface Post {
  contents: Content[] | Category[];
  totalCount: number;
  offset: number;
  limit: number;
}

export interface Content {
  id: string;
  createdAt?: string;
  updatedAt?: string;
  title: string;
  body?: string;
  category: Category[];
  image_first?: string;
  image_second?: string;
  image_third?: string;
  image_forth?: string;
  cover_image?: CoverImage;
}

export interface Category {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
}

export interface CoverImage {
  url: string;
}

export interface Category {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
}
